version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/code
    working_dir: /code
    command: "python /code/app.py"
    tty: true
    ports:
      - 8999:5000
