version: "3.4"
services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    command: "bash start.sh"
    ports:
      - "1040:5000"
    healthcheck:
      test: curl --fail -s http://localhost:5000/ || exit 1
      interval: 3s
      timeout: 10s
      retries: 3
